name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request: {}

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: "Lints"
    runs-on: ubuntu-latest

    steps:
      - uses: wyvox/action@v1
      - run: pnpm build
      - run: pnpm lint

  test:
    name: "Test ${{ matrix.dir }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dir:
          - "ember-scoped-css"
          - "stylelint-ember-scoped-css"
          - "test-apps/v2-addon-bundled"
          - "test-apps/vite-app"
          - "test-apps/vite-app-with-compat"
          - "test-apps/vite-app-with-compat-pods"

    steps:
      - uses: wyvox/action@v1
      - run: pnpm build
      - run: pnpm test
        working-directory: ${{ matrix.dir }}

  floating:
    name: "Floating ${{ matrix.dir }}"
    runs-on: ubuntu-latest
    needs: "test"
    strategy:
      fail-fast: false
      matrix:
        dir:
          - "ember-scoped-css"
          - "stylelint-ember-scoped-css"
          - "test-apps/v2-addon-bundled"
          - "test-apps/vite-app"
          - "test-apps/vite-app-with-compat"
          - "test-apps/vite-app-with-compat-pods"

    steps:
      - uses: wyvox/action@v1
        with:
          no-lockfile: true
      - run: pnpm build
      - name: Run Tests
        run: pnpm test
        working-directory: ${{ matrix.dir }}
