name: Fixture Tests

on:
  push:
    branches:
      - main
      - master
  pull_request: {}

concurrency:
  group: fixture-tests-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm test:fixture
